# gen_graphs.ps1 - writes the Blueprint graphs of the in-game editor as
# clipboard T3D, ready to paste into the UE 5.3 editor (D:\SkinLiveUE).
#
#   .\gen_graphs.ps1            -> D:\SkinLiveUE\paste\editor_1..4.txt, bootstrap.txt
#
# ---- why FOUR pastes for the editor widget -----------------------------------
# A pasted call to a custom event that is not compiled yet cannot find its
# function, and UE keeps orphaned DATA pins on reconstruct but never EXEC pins
# (K2Node.cpp: ESaveOrphanPinMode::SaveAllButExec) - the call would arrive with
# its exec wires cut. So the events go in by dependency level, compiling
# between pastes:
#   1  SendCmd, TrySwap, Splash             (call nothing of ours)
#   2  SendMouse, Walk, Close, MountLive    (call level 1)
#   3  Open, ReloadAll, AutoStart           (call levels 1-2)
#   4  Toggle, Tick, mouse, wheel
# The bootstrap is pasted last, once WBP_SkinLiveEditor_C is compiled. Its
# AutoTick timer (once a second) announces each hero spawned (-> AutoStart)
# and presses Project Galacta's F7 when Skin Studio asks (SkinLiveGalToggle).
#
# ---- what the format relies on (UE 5.3 source) -------------------------------
# Paste calls ReconstructNode on every node (EdGraphUtilities.cpp), which
# rebuilds pins from the real function signature and re-wires old pins by NAME
# and DIRECTION only (K2Node.cpp DoPinsMatchForReconstruction). So a pin here
# needs the right name; its type matters only when it carries a default. A
# default survives only if it differs from AutogeneratedDefaultValue, so that
# is always written empty. For Each loops carry ResolvedWildcardType, without
# which the macro never learns its element type (the old paste failure).
# -Hosted: the bootstrap for the merged !!SkinStudio mod, which creates this
# bootstrap itself and owns F8 (its colour panel's Studio button opens ours),
# so no F8 here. F6, AutoTick, the Galacta host and the splash all stay.
param([string]$Out = 'D:\SkinLiveUE\paste', [switch]$Hosted)
$ErrorActionPreference = 'Stop'

$EditorClass = '/Game/Marvel/SkinLive/UI/Widgets/WBP_SkinLiveEditor.WBP_SkinLiveEditor_C'
$EditorClassRef = "WidgetBlueprintGeneratedClass'`"$EditorClass`"'"

$script:G = $null
function New-Graph([int]$tag) {
    $script:G = @{ Tag = $tag; Nodes = New-Object System.Collections.ArrayList; Seq = 0; Count = @{} }
}
function New-Guid32 {
    $script:G.Seq++
    '5C1E{0:X4}{1:X8}0000000000000000' -f $script:G.Tag, $script:G.Seq
}

# ---- types: exec bool int real float string name obj:<path> class:<path>
#             struct:<path> byte:<enum path> wild   (+ '[]' suffix for arrays)
function Pin-Type([string]$t) {
    $arr = $t.EndsWith('[]'); if ($arr) { $t = $t.Substring(0, $t.Length - 2) }
    $cat = $t; $sub = ''; $obj = 'None'
    if ($t -match '^(obj|class|struct|byte):(.+)$') {
        $kind = $Matches[1]; $path = $Matches[2]
        switch ($kind) {
            # ★ UE 5.3 writes a pin's type object as "/Script/CoreUObject.Class'<path>'".
            # The UE4 form Class'"<path>"' does not resolve here: the pin comes back
            # untyped, so casts report "the type of Object is undetermined" and every
            # pin carrying a default is orphaned.
            'obj'    { $cat = 'object'; $obj = "`"/Script/CoreUObject.Class'$path'`"" }
            'class'  { $cat = 'class';  $obj = "`"/Script/CoreUObject.Class'$path'`"" }
            'struct' { $cat = 'struct'; $obj = "`"/Script/CoreUObject.ScriptStruct'$path'`"" }
            'byte'   { $cat = 'byte';   $obj = "`"/Script/CoreUObject.Enum'$path'`"" }
        }
    } elseif ($t -eq 'real') { $cat = 'real'; $sub = 'double' }
    elseif ($t -eq 'float') { $cat = 'real'; $sub = 'float' }
    elseif ($t -eq 'wild') { $cat = 'wildcard' }
    @{ Cat = $cat; Sub = $sub; Obj = $obj; Container = $(if ($arr) { 'Array' } else { 'None' }) }
}

function Add-Node([string]$class, [string[]]$props, [int]$x, [int]$y) {
    $short = $class.Substring($class.LastIndexOf('.') + 1)
    $k = [int]$script:G.Count[$short]; $script:G.Count[$short] = $k + 1
    $n = @{ Name = ('{0}_{1}' -f $short, (1000 * $script:G.Tag + 100 + $k)); Class = $class; Props = @($props); X = $x; Y = $y
            Guid = (New-Guid32); Pins = [ordered]@{}; Extra = @() }
    [void]$script:G.Nodes.Add($n)
    $n
}

function Get-Pin($n, [string]$name, [bool]$out, [string]$type) {
    if ($n.Pins.Contains($name)) { return $n.Pins[$name] }
    $execNames = @('execute', 'then', 'else', 'Exec', 'LoopBody', 'Completed', 'CastFailed', 'Pressed', 'Released')
    if (-not $type) { $type = if ($execNames -contains $name -or $name -match '^then_\d+$') { 'exec' } else { 'wild' } }
    $p = @{ Name = $name; Out = $out; Type = (Pin-Type $type); Default = $null; DefObj = $null
            Links = New-Object System.Collections.ArrayList; Id = (New-Guid32) }
    $n.Pins[$name] = $p
    $p
}

# a wire: output pin of $a -> input pin of $b
function Wire($a, [string]$pa, $b, [string]$pb) {
    $x = Get-Pin $a $pa $true ''
    $y = Get-Pin $b $pb $false ''
    [void]$x.Links.Add(('{0} {1}' -f $b.Name, $y.Id))
    [void]$y.Links.Add(('{0} {1}' -f $a.Name, $x.Id))
}

# an input pin with a literal default
function Def($n, [string]$pin, [string]$type, [string]$value) {
    $p = Get-Pin $n $pin $false $type
    $p.Type = Pin-Type $type
    if ($type -like 'class:*' -or $type -like 'obj:*') { $p.DefObj = $value } else { $p.Default = $value }
}

# declare an output pin's type (for event parameters)
function OutPin($n, [string]$pin, [string]$type) { $p = Get-Pin $n $pin $true $type; $p.Type = Pin-Type $type }

# ★ A macro instance's INPUT exec pin is called 'execute', not 'Exec' (only its
# outputs are LoopBody / Completed). Wiring to 'Exec' drops the link silently -
# exec pins are never kept as orphans - so the loop is never entered, the whole
# chain below it is pruned as unreachable, and it all still compiles clean.
# ---- node makers
function Call([string]$owner, [string]$fn, [int]$x, [int]$y) {
    # ★ guards the case-insensitivity trap: a local like $gs IS the constant $GS,
    # so a node object can silently land here and emit MemberParent=Hashtable,
    # which UE drops on paste without a word
    if (-not ($owner.StartsWith('/') -or $owner.StartsWith('Class') -or $owner.Contains('Blueprint'))) {
        throw "Call: '$fn' has a bad owner '$owner' - a variable was clobbered"
    }
    $parent = if ($owner -like '/*') { "Class'`"$owner`"'" } else { $owner }
    Add-Node '/Script/BlueprintGraph.K2Node_CallFunction' @("FunctionReference=(MemberParent=$parent,MemberName=`"$fn`")") $x $y
}
function CallSelf([string]$fn, [int]$x, [int]$y) {
    Add-Node '/Script/BlueprintGraph.K2Node_CallFunction' @("FunctionReference=(MemberName=`"$fn`",bSelfContext=True)") $x $y
}
function CallEditor([string]$fn, [int]$x, [int]$y) {
    Add-Node '/Script/BlueprintGraph.K2Node_CallFunction' @("FunctionReference=(MemberParent=$EditorClassRef,MemberName=`"$fn`")") $x $y
}
function CustomEvent([string]$name, [int]$x, [int]$y, [string[]]$params) {
    $n = Add-Node '/Script/BlueprintGraph.K2Node_CustomEvent' @("CustomFunctionName=`"$name`"") $x $y
    $d = Get-Pin $n 'OutputDelegate' $true 'wild'
    $d.Type = @{ Cat = 'delegate'; Sub = ''; Obj = 'None'; Container = 'None'; Member = "(MemberName=`"$name`")" }
    $d.Hidden = $true
    [void](Get-Pin $n 'then' $true 'exec')
    foreach ($spec in $params) {
        $pn, $pt = $spec -split '=', 2
        OutPin $n $pn $pt
        $t = Pin-Type $pt
        $obj = if ($t.Obj -ne 'None') { ',PinSubCategoryObject=' + $t.Obj } else { '' }
        $sub = if ($t.Sub) { ',PinSubCategory="' + $t.Sub + '"' } else { '' }
        $n.Extra += ('CustomProperties UserDefinedPin (PinName="{0}",PinType=(PinCategory="{1}"{2}{3}),DesiredPinDirection=EGPD_Output)' -f $pn, $t.Cat, $sub, $obj)
    }
    $n
}
function Branch([int]$x, [int]$y) { Add-Node '/Script/BlueprintGraph.K2Node_IfThenElse' @() $x $y }
function CallArray([string]$fn, [int]$x, [int]$y) {
    Add-Node '/Script/BlueprintGraph.K2Node_CallArrayFunction' @("FunctionReference=(MemberParent=Class'`"/Script/Engine.KismetArrayLibrary`"',MemberName=`"$fn`")") $x $y
}
# ★ A pasted For Each Loop stays WILDCARD: ResolvedWildcardType is only ever set
# from a live connection change, and nothing re-applies it on paste, so the
# element pin has no type and any cast off it fails to compile. Array_Length and
# Get (a copy) DO re-type themselves on paste (both call PropagateArrayTypeInfo /
# PropagatePinType from PostReconstructNode), and a For Loop is plain ints - so
# build the loop from those three instead.
function ArrayLoop($arrNode, [string]$arrPin, [int]$x, [int]$y) {
    $len = CallArray 'Array_Length' $x ($y + 200)
    Wire $arrNode $arrPin $len 'TargetArray'
    $sub = Call '/Script/Engine.KismetMathLibrary' 'Subtract_IntInt' ($x + 200) ($y + 200)
    Wire $len 'ReturnValue' $sub 'A'; Def $sub 'B' 'int' '1'
    $loop = Macro 'ForLoop' '' ($x + 400) $y
    Def $loop 'FirstIndex' 'int' '0'; Wire $sub 'ReturnValue' $loop 'LastIndex'
    $item = Add-Node '/Script/BlueprintGraph.K2Node_GetArrayItem' @() ($x + 620) ($y + 200)
    Wire $arrNode $arrPin $item 'Array'
    Wire $loop 'Index' $item 'Dimension 1'
    @{ Loop = $loop; Item = $item }
}
function ExecSeq([int]$x, [int]$y) { Add-Node '/Script/BlueprintGraph.K2Node_ExecutionSequence' @() $x $y }
function Cast([string]$cls, [int]$x, [int]$y) {
    Add-Node '/Script/BlueprintGraph.K2Node_DynamicCast' @("TargetType=Class'`"$cls`"'") $x $y
}
function GetMember([string]$var, [int]$x, [int]$y) {
    Add-Node '/Script/BlueprintGraph.K2Node_VariableGet' @("VariableReference=(MemberName=`"$var`",bSelfContext=True)") $x $y
}
function GetVarOf([string]$cls, [string]$var, [int]$x, [int]$y) {
    Add-Node '/Script/BlueprintGraph.K2Node_VariableGet' @("VariableReference=(MemberParent=Class'`"$cls`"',MemberName=`"$var`")") $x $y
}
function SetVarOf([string]$cls, [string]$var, [int]$x, [int]$y) {
    Add-Node '/Script/BlueprintGraph.K2Node_VariableSet' @("VariableReference=(MemberParent=Class'`"$cls`"',MemberName=`"$var`")") $x $y
}
function Macro([string]$which, [string]$wildObj, [int]$x, [int]$y) {
    $p = @("MacroGraphReference=(MacroGraph=EdGraph'`"/Engine/EditorBlueprintResources/StandardMacros.StandardMacros:$which`"',GraphBlueprint=Blueprint'`"/Engine/EditorBlueprintResources/StandardMacros.StandardMacros`"',GraphGuid=00000000000000000000000000000000)")
    if ($wildObj) { $p += 'ResolvedWildcardType=(PinCategory="object",PinSubCategoryObject="/Script/CoreUObject.Class''{0}''")' -f $wildObj }
    Add-Node '/Script/BlueprintGraph.K2Node_MacroInstance' $p $x $y
}
function InputKey([string]$key, [bool]$consume, [int]$x, [int]$y) {
    Add-Node '/Script/BlueprintGraph.K2Node_InputKey' @("InputKey=$key", "bConsumeInput=$(if ($consume) { 'True' } else { 'False' })", 'bExecuteWhenPaused=False', 'bOverrideParentBinding=True') $x $y
}
function OverrideEvent([string]$cls, [string]$fn, [int]$x, [int]$y) {
    Add-Node '/Script/BlueprintGraph.K2Node_Event' @("EventReference=(MemberParent=Class'`"$cls`"',MemberName=`"$fn`")", 'bOverrideFunction=True') $x $y
}
function BoundEvent([string]$widgetVar, [string]$delegate, [string]$sig, [int]$x, [int]$y) {
    $k = [int]$script:G.Count['K2Node_ComponentBoundEvent']
    Add-Node '/Script/BlueprintGraph.K2Node_ComponentBoundEvent' @(
        "DelegatePropertyName=`"$delegate`"",
        "DelegateOwnerClass=Class'`"/Script/UMG.Button`"'",
        "ComponentPropertyName=`"$widgetVar`"",
        "EventReference=(MemberParent=Package'`"/Script/UMG`"',MemberName=`"$sig`")",
        'bInternalEvent=True',
        ("CustomFunctionName=`"BndEvt__WBP_SkinLiveEditor_{0}_K2Node_ComponentBoundEvent_{1}_{2}`"" -f $widgetVar, (100 + $k), $sig)) $x $y
}

# string building: Concat_StrStr chains. $parts: node/pin pairs or literals.
#   @( 'SLC_', @($node,'ReturnValue'), '_' )  -> returns the last Concat node
function Concat-Chain([object[]]$parts, [int]$x, [int]$y) {
    $prev = $null
    for ($i = 1; $i -lt $parts.Count; $i++) {
        $c = Call '/Script/Engine.KismetStringLibrary' 'Concat_StrStr' ($x + 180 * $i) $y
        if ($i -eq 1) { Set-StrInput $c 'A' $parts[0] } else { Wire $prev 'ReturnValue' $c 'A' }
        Set-StrInput $c 'B' $parts[$i]
        $prev = $c
    }
    $prev
}
function Set-StrInput($n, [string]$pin, $part) {
    if ($part -is [string]) { Def $n $pin 'string' $part }
    else { Wire $part[0] $part[1] $n $pin }
}

# ---- emit
function Emit-Graph {
    $sb = New-Object System.Text.StringBuilder
    foreach ($n in $script:G.Nodes) {
        [void]$sb.AppendLine(('Begin Object Class={0} Name="{1}"' -f $n.Class, $n.Name))
        foreach ($p in $n.Props) { [void]$sb.AppendLine('   ' + $p) }
        [void]$sb.AppendLine(('   NodePosX={0}' -f $n.X))
        [void]$sb.AppendLine(('   NodePosY={0}' -f $n.Y))
        [void]$sb.AppendLine(('   NodeGuid={0}' -f $n.Guid))
        foreach ($p in $n.Pins.Values) {
            $t = $p.Type
            $mem = if ($t.Member) { $t.Member } else { '()' }
            $dir = if ($p.Out) { 'Direction="EGPD_Output",' } else { '' }
            $def = ''
            if ($null -ne $p.DefObj) { $def = 'DefaultObject="{0}",' -f $p.DefObj }
            elseif ($null -ne $p.Default) { $def = 'DefaultValue="{0}",' -f $p.Default }
            $links = ''
            if ($p.Links.Count -gt 0) { $links = 'LinkedTo=(' + (($p.Links | ForEach-Object { $_ + ',' }) -join '') + '),' }
            $hid = if ($p.Hidden) { 'True' } else { 'False' }
            [void]$sb.AppendLine(('      CustomProperties Pin (PinId={0},PinName="{1}",{2}PinType.PinCategory="{3}",PinType.PinSubCategory="{4}",PinType.PinSubCategoryObject={5},PinType.PinSubCategoryMemberReference={6},PinType.PinValueType=(),PinType.ContainerType={7},PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,{8}AutogeneratedDefaultValue="",{9}PersistentGuid=00000000000000000000000000000000,bHidden={10},bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)' -f `
                $p.Id, $p.Name, $dir, $t.Cat, $t.Sub, $t.Obj, $mem, $t.Container, $def, $links, $hid))
        }
        foreach ($e in $n.Extra) { [void]$sb.AppendLine('      ' + $e) }
        [void]$sb.AppendLine('End Object')
    }
    $sb.ToString()
}
function Save-Graph([string]$file) {
    New-Item -ItemType Directory -Force -Path $Out | Out-Null
    $path = Join-Path $Out $file
    [IO.File]::WriteAllText($path, (Emit-Graph), (New-Object System.Text.UTF8Encoding($false)))
    '{0,-18} {1,3} nodes  {2,6} bytes' -f $file, $script:G.Nodes.Count, (Get-Item $path).Length
}

$GS  = '/Script/Engine.GameplayStatics'
$KM  = '/Script/Engine.KismetMathLibrary'
$KS  = '/Script/Engine.KismetSystemLibrary'
$KSt = '/Script/Engine.KismetStringLibrary'
$KR  = '/Script/Engine.KismetRenderingLibrary'
$WL  = '/Script/UMG.WidgetLayoutLibrary'
$WB  = '/Script/UMG.WidgetBlueprintLibrary'
$SL  = '/Script/UMG.SlateBlueprintLibrary'
$UW  = '/Script/UMG.UserWidget'
$WG  = '/Script/UMG.Widget'
$MIC = '/Script/Engine.MaterialInstanceConstant'
$MID = '/Script/Engine.MaterialInstanceDynamic'
$VisEnum = 'byte:/Script/UMG.ESlateVisibility'   # not $VIS: a $vis parameter would be the same variable

function Flag-Check([string]$slot, $execFrom, [string]$execPin, [int]$x, [int]$y) {
    # DoesSaveGameExist(slot) -> Branch -> DeleteGameInSlot(slot); returns the delete node
    $ds = Call $GS 'DoesSaveGameExist' $x $y; Def $ds 'SlotName' 'string' $slot; Def $ds 'UserIndex' 'int' '0'
    Wire $execFrom $execPin $ds 'execute'
    $br = Branch ($x + 260) $y; Wire $ds 'then' $br 'execute'; Wire $ds 'ReturnValue' $br 'Condition'
    $dg = Call $GS 'DeleteGameInSlot' ($x + 460) $y; Def $dg 'SlotName' 'string' $slot; Def $dg 'UserIndex' 'int' '0'
    Wire $br 'then' $dg 'execute'
    $dg
}
# SendCmd's nodes written out in place, for level-1 events that cannot CALL
# SendCmd (it is pasted in the same block, so the call would lose its exec
# wires - see the header). $cmdParts go after "SLC_<ms>_", as for Concat-Chain.
function Inline-Send($execFrom, [string]$execPin, [object[]]$cmdParts, [int]$x, [int]$y) {
    $rt = Call $GS 'GetRealTimeSeconds' $x ($y + 160)
    $mu = Call $KM 'Multiply_DoubleDouble' ($x + 200) ($y + 160); Wire $rt 'ReturnValue' $mu 'A'; Def $mu 'B' 'real' '1000.000000'
    $ro = Call $KM 'Round' ($x + 400) ($y + 160); Wire $mu 'ReturnValue' $ro 'A'
    $mstr = Call $KSt 'Conv_IntToString' ($x + 600) ($y + 160); Wire $ro 'ReturnValue' $mstr 'InInt'
    $nm = Concat-Chain (@('SLC_', @($mstr, 'ReturnValue'), '_') + $cmdParts) ($x + 200) ($y + 280)
    $ld = Call $GS 'LoadGameFromSlot' ($x + 250) $y; Def $ld 'SlotName' 'string' 'HighlightSettings'; Def $ld 'UserIndex' 'int' '0'
    $sv = Call $GS 'SaveGameToSlot' ($x + 500) $y; Def $sv 'UserIndex' 'int' '0'
    Wire $execFrom $execPin $ld 'execute'; Wire $ld 'then' $sv 'execute'
    Wire $ld 'ReturnValue' $sv 'SaveGameObject'; Wire $nm 'ReturnValue' $sv 'SlotName'
    $sv
}
function Send-Literal($execFrom, [string]$execPin, [string]$cmd, [int]$x, [int]$y) {
    $c = CallSelf 'SendCmd' $x $y; Def $c 'Cmd' 'string' $cmd; Wire $execFrom $execPin $c 'execute'; $c
}
# Rivals owns the input mode in a match: MarvelHUD counts the menus that need
# the mouse and restores gameplay mode when none do, which beat our own
# SetInputMode. So Open/Close ask the HUD itself (NeedInputModeUI /
# StopNeedInputModeUI). Our project has no MarvelHUD class, so these are
# authored against stock stand-ins that patch_hud_calls.ps1 rewrites after the
# cook - the guard's class literal /Script/Engine.Info becomes MarvelHUD, and
# the two virtual calls are renamed. Returns the Branch (then = a MarvelHUD) and
# the GetHUD node to call on.
function Hud-Guard($pcNode, [int]$x, [int]$y) {
    $hud = Call '/Script/Engine.PlayerController' 'GetHUD' $x ($y + 160); Wire $pcNode 'ReturnValue' $hud 'self'
    $cls = Call $GS 'GetObjectClass' ($x + 200) ($y + 160); Wire $hud 'ReturnValue' $cls 'Object'
    $isc = Call $KM 'ClassIsChildOf' ($x + 400) ($y + 160); Wire $cls 'ReturnValue' $isc 'TestClass'
    Def $isc 'ParentClass' 'class:/Script/CoreUObject.Object' '/Script/Engine.Info'
    $br = Branch ($x + 600) $y; Wire $isc 'ReturnValue' $br 'Condition'
    @{ Branch = $br; Hud = $hud }
}

function Set-Vis($execFrom, [string]$execPin, [string]$widgetVar, [string]$want, [int]$x, [int]$y) {
    $v = GetMember $widgetVar $x ($y + 120)
    $s = Call $WG 'SetVisibility' ($x + 180) $y
    Wire $v $widgetVar $s 'self'; Def $s 'InVisibility' $VisEnum $want
    Wire $execFrom $execPin $s 'execute'
    $s
}

# =========================================================== editor, paste 1
New-Graph 1
# SendCmd(Cmd): SaveGameToSlot(<borrowed save>, "SLC_<ms>_<Cmd>")
$e = CustomEvent 'SendCmd' 0 0 @('Cmd=string')
$rt = Call $GS 'GetRealTimeSeconds' 0 160
$mul = Call $KM 'Multiply_DoubleDouble' 200 160; Wire $rt 'ReturnValue' $mul 'A'; Def $mul 'B' 'real' '1000.000000'
$rnd = Call $KM 'Round' 400 160; Wire $mul 'ReturnValue' $rnd 'A'
$its = Call $KSt 'Conv_IntToString' 600 160; Wire $rnd 'ReturnValue' $its 'InInt'
$name = Concat-Chain @('SLC_', @($its, 'ReturnValue'), '_', @($e, 'Cmd')) 600 280
$load = Call $GS 'LoadGameFromSlot' 300 0; Def $load 'SlotName' 'string' 'HighlightSettings'; Def $load 'UserIndex' 'int' '0'
$save = Call $GS 'SaveGameToSlot' 1400 0; Def $save 'UserIndex' 'int' '0'
Wire $e 'then' $load 'execute'; Wire $load 'then' $save 'execute'
Wire $load 'ReturnValue' $save 'SaveGameObject'; Wire $name 'ReturnValue' $save 'SlotName'

# TrySwap(MID, MIC, Param, Force, Pak, Prefix): re-import one texture
# parameter if flagged. Pak is the built-mod manifest Walk read
# (<pak>|<order>|<prefix>|<texture>|<texture>|...|); a texture listed there is
# loaded out of the pak the PC built and MountLive mounted - Project Galacta's
# method: a pak mounted while the game runs, and an asset at a path nothing has
# loaded yet, so the load is fresh. The path is the vanilla one with its first
# Len(Prefix) characters replaced (the PC renamed each package the same way, at
# equal length). Anything else, or a pak asset that will not load, takes the
# PNG route as before.
$e = CustomEvent 'TrySwap' 0 600 @("MID=obj:$MID", "MIC=obj:$MIC", 'Param=name', 'Force=bool', 'Pak=string', 'Prefix=string')
$gt = Call $MIC 'K2_GetTextureParameterValue' 300 600; Wire $e 'MIC' $gt 'self'; Wire $e 'Param' $gt 'ParameterName'; Wire $e 'then' $gt 'execute'
$iv = Call $KS 'IsValid' 560 760; Wire $gt 'ReturnValue' $iv 'Object'
$b1 = Branch 600 600; Wire $gt 'then' $b1 'execute'; Wire $iv 'ReturnValue' $b1 'Condition'
$on = Call $KS 'GetObjectName' 560 900; Wire $gt 'ReturnValue' $on 'Object'
$fn = Concat-Chain @('SLT_', @($on, 'ReturnValue')) 700 900
$ds = Call $GS 'DoesSaveGameExist' 900 600; Wire $fn 'ReturnValue' $ds 'SlotName'; Def $ds 'UserIndex' 'int' '0'; Wire $b1 'then' $ds 'execute'
$or = Call $KM 'BooleanOR' 1150 760; Wire $e 'Force' $or 'A'; Wire $ds 'ReturnValue' $or 'B'
$b2 = Branch 1200 600; Wire $ds 'then' $b2 'execute'; Wire $or 'ReturnValue' $b2 'Condition'
$cd = Call $KS 'GetProjectContentDirectory' 1100 1040
$path = Concat-Chain @(@($cd, 'ReturnValue'), 'SkinStudioLive/', @($on, 'ReturnValue'), '.png') 1100 1040
# the built mod first: is this texture in the mounted pak?
$key = Concat-Chain @('|', @($on, 'ReturnValue'), '|') 1200 1300
$has = Call $KSt 'Contains' 1600 1300; Wire $e 'Pak' $has 'SearchIn'; Wire $key 'ReturnValue' $has 'Substring'
$bp = Branch 1450 600; Wire $b2 'then' $bp 'execute'; Wire $has 'ReturnValue' $bp 'Condition'
$pn = Call $KS 'GetPathName' 1500 1500; Wire $gt 'ReturnValue' $pn 'Object'
$pl = Call $KSt 'Len' 1500 1640; Wire $e 'Prefix' $pl 'S'
$rc = Call $KSt 'RightChop' 1750 1500; Wire $pn 'ReturnValue' $rc 'SourceString'; Wire $pl 'ReturnValue' $rc 'Count'
$np = Concat-Chain @(@($e, 'Prefix'), @($rc, 'ReturnValue')) 1800 1500
$ms = Call $KS 'MakeSoftObjectPath' 2200 1500; Wire $np 'ReturnValue' $ms 'PathString'
$cv = Call $KS 'Conv_SoftObjPathToSoftObjRef' 2450 1500; Wire $ms 'ReturnValue' $cv 'SoftObjectPath'
$la = Call $KS 'LoadAsset_Blocking' 1700 300; Wire $bp 'then' $la 'execute'; Wire $cv 'ReturnValue' $la 'Asset'
$ct = Cast '/Script/Engine.Texture' 1950 300; Wire $la 'then' $ct 'execute'; Wire $la 'ReturnValue' $ct 'Object'
$sp = Call $MID 'SetTextureParameterValue' 2250 300
Wire $ct 'then' $sp 'execute'; Wire $e 'MID' $sp 'self'; Wire $e 'Param' $sp 'ParameterName'; Wire $ct 'AsTexture' $sp 'Value'
# proof for the panel: pk_<texture> = this one really came out of the built
# mod (a PNG fallback looks identical on the hero, so only the game can say)
$null = Inline-Send $sp 'then' @('pk_', @($on, 'ReturnValue')) 2500 300
# the PNG route: not in the pak, or the pak asset did not load
$im = Call $KR 'ImportFileAsTexture2D' 1500 600; Wire $path 'ReturnValue' $im 'Filename'
Wire $bp 'else' $im 'execute'; Wire $ct 'CastFailed' $im 'execute'
$iv2 = Call $KS 'IsValid' 1750 760; Wire $im 'ReturnValue' $iv2 'Object'
$b3 = Branch 1800 600; Wire $im 'then' $b3 'execute'; Wire $iv2 'ReturnValue' $b3 'Condition'
$st = Call $MID 'SetTextureParameterValue' 2050 600
Wire $b3 'then' $st 'execute'; Wire $e 'MID' $st 'self'; Wire $e 'Param' $st 'ParameterName'; Wire $im 'ReturnValue' $st 'Value'

# Splash: the Variant wordmark at login, on its own - her call 2026-09-26: not
# on Project Galacta's intro slide, separately. The bootstrap calls this on
# the login level. It borrows the panel's Image: bottom centre, 22% of the
# screen wide, for five seconds, then hidden again unless the panel opened.
$e = CustomEvent 'Splash' 0 1900
$scs = GetMember 'Screen' 0 2060
$sbt = Call '/Script/UMG.Image' 'SetBrushFromTexture' 250 1900; Wire $e 'then' $sbt 'execute'; Wire $scs 'Screen' $sbt 'self'
Def $sbt 'Texture' 'obj:/Script/Engine.Texture2D' '/Game/Marvel/SkinLive/UI/Textures/T_VariantWordmark.T_VariantWordmark'
Def $sbt 'bMatchSize' 'bool' 'false'
$svs = Call $WL 'GetViewportSize' 250 2200
$sbv = Call $KM 'BreakVector2D' 450 2200; Wire $svs 'ReturnValue' $sbv 'InVec'
$ssc = Call $WL 'GetViewportScale' 450 2340
# pixels: 22% of the width, the wordmark's 1200x377 aspect
$swp = Call $KM 'Multiply_DoubleDouble' 650 2200; Wire $sbv 'X' $swp 'A'; Def $swp 'B' 'real' '0.220000'
$shp = Call $KM 'Multiply_DoubleDouble' 850 2200; Wire $swp 'ReturnValue' $shp 'A'; Def $shp 'B' 'real' '0.314167'
# desired size is in slate units: pixels / viewport scale, as the panel frames do
$sws = Call $KM 'Divide_DoubleDouble' 1050 2200; Wire $swp 'ReturnValue' $sws 'A'; Wire $ssc 'ReturnValue' $sws 'B'
$shs = Call $KM 'Divide_DoubleDouble' 1050 2320; Wire $shp 'ReturnValue' $shs 'A'; Wire $ssc 'ReturnValue' $shs 'B'
$ssz = Call $KM 'MakeVector2D' 1250 2200; Wire $sws 'ReturnValue' $ssz 'X'; Wire $shs 'ReturnValue' $ssz 'Y'
# bottom centre, 6% up from the bottom edge
$spx = Call $KM 'Multiply_DoubleDouble' 650 2460; Wire $sbv 'X' $spx 'A'; Def $spx 'B' 'real' '0.500000'
$spy = Call $KM 'Multiply_DoubleDouble' 650 2580; Wire $sbv 'Y' $spy 'A'; Def $spy 'B' 'real' '0.940000'
$sps = Call $KM 'MakeVector2D' 850 2460; Wire $spx 'ReturnValue' $sps 'X'; Wire $spy 'ReturnValue' $sps 'Y'
$sp1 = Call $UW 'SetPositionInViewport' 500 1900; Wire $sbt 'then' $sp1 'execute'; Wire $sps 'ReturnValue' $sp1 'Position'; Def $sp1 'bRemoveDPIScale' 'bool' 'true'
$sp2 = Call $UW 'SetAlignmentInViewport' 750 1900; Wire $sp1 'then' $sp2 'execute'; Def $sp2 'Alignment' 'struct:/Script/CoreUObject.Vector2D' '(X=0.500000,Y=1.000000)'
$sp3 = Call $UW 'SetDesiredSizeInViewport' 1000 1900; Wire $sp2 'then' $sp3 'execute'; Wire $ssz 'ReturnValue' $sp3 'Size'
$sp4 = Set-Vis $sp3 'then' 'Screen' 'HitTestInvisible' 1250 1900
$sdl = Call $KS 'Delay' 1650 1900; Wire $sp4 'then' $sdl 'execute'; Def $sdl 'Duration' 'float' '5.000000'
$shv = GetMember 'Hit' 1850 2060
$shi = Call $WG 'IsVisible' 2000 2060; Wire $shv 'Hit' $shi 'self'
$sbr = Branch 1900 1900; Wire $sdl 'then' $sbr 'execute'; Wire $shi 'ReturnValue' $sbr 'Condition'
$null = Set-Vis $sbr 'else' 'Screen' 'Collapsed' 2150 1900
Save-Graph 'editor_1.txt'

# =========================================================== editor, paste 2
New-Graph 2
# SendMouse(Verb): "<Verb>_<x>_<y>_<w>_<h>", mouse in the Hit button's own space
$e = CustomEvent 'SendMouse' 0 0 @('Verb=string')
$mp = Call $WL 'GetMousePositionOnPlatform' 250 0; Wire $e 'then' $mp 'execute'
$hv = GetMember 'Hit' 0 200
$gg = Call $WG 'GetCachedGeometry' 180 200; Wire $hv 'Hit' $gg 'self'
$al = Call $SL 'AbsoluteToLocal' 420 200; Wire $gg 'ReturnValue' $al 'Geometry'; Wire $mp 'ReturnValue' $al 'AbsoluteCoordinate'
$ls = Call $SL 'GetLocalSize' 420 340; Wire $gg 'ReturnValue' $ls 'Geometry'
$bp = Call $KM 'BreakVector2D' 660 200; Wire $al 'ReturnValue' $bp 'InVec'
$bs = Call $KM 'BreakVector2D' 660 340; Wire $ls 'ReturnValue' $bs 'InVec'
$strs = @()
$i = 0
foreach ($src in @(@($bp, 'X'), @($bp, 'Y'), @($bs, 'X'), @($bs, 'Y'))) {
    $r = Call $KM 'Round' 880 (200 + 90 * $i); Wire $src[0] $src[1] $r 'A'
    $s = Call $KSt 'Conv_IntToString' 1060 (200 + 90 * $i); Wire $r 'ReturnValue' $s 'InInt'
    $strs += , @($s, 'ReturnValue'); $i++
}
$msg = Concat-Chain @(@($e, 'Verb'), '_', $strs[0], '_', $strs[1], '_', $strs[2], '_', $strs[3]) 1200 560
$sc = CallSelf 'SendCmd' 600 0; Wire $mp 'then' $sc 'execute'; Wire $msg 'ReturnValue' $sc 'Cmd'

# Walk(Announce, Force): every material slot of the pawn's attached actors
$e = CustomEvent 'Walk' 0 900 @('Announce=bool', 'Force=bool')
# the built-mod manifest, read once per walk. Blueprint has no file reader of
# its own; the stand-in GetConsoleVariableStringValue(path) is repointed after
# the cook to Rivals' MarvelFileUtil.LoadFromFileWithFullFilePath (same shape:
# one string in, one string out) by patch_live_calls.ps1. "||||" means none,
# and is also what a missing file reads as - never a stale earlier read.
$cdw = Call $KS 'GetProjectContentDirectory' -400 700
$mfw = Concat-Chain @(@($cdw, 'ReturnValue'), 'SkinStudioLive/_pak.txt') -400 700
$few = Call '/Script/Engine.BlueprintPathsLibrary' 'FileExists' -100 820; Wire $mfw 'ReturnValue' $few 'InPath'
$bfw = Branch 100 700; Wire $e 'then' $bfw 'execute'; Wire $few 'ReturnValue' $bfw 'Condition'
$rdw = Call $KS 'GetConsoleVariableStringValue' 300 600; Wire $bfw 'then' $rdw 'execute'; Wire $mfw 'ReturnValue' $rdw 'VariableName'
$sel = Call $KM 'SelectString' 500 760; Wire $rdw 'ReturnValue' $sel 'A'; Def $sel 'B' 'string' '||||'; Wire $few 'ReturnValue' $sel 'bPickA'
$paw = Call $KSt 'ParseIntoArray' 700 760; Wire $sel 'ReturnValue' $paw 'SourceString'; Def $paw 'Delimiter' 'string' '|'; Def $paw 'CullEmptyStrings' 'bool' 'false'
$pxw = Add-Node '/Script/BlueprintGraph.K2Node_GetArrayItem' @() 950 760
Wire $paw 'ReturnValue' $pxw 'Array'; Def $pxw 'Dimension 1' 'int' '2'
$pp = Call $GS 'GetPlayerPawn' 0 1060; Def $pp 'PlayerIndex' 'int' '0'
$ga = Call '/Script/Engine.Actor' 'GetAttachedActors' 200 1060; Wire $pp 'ReturnValue' $ga 'self'
Def $ga 'bResetArray' 'bool' 'true'; Def $ga 'bRecursivelyIncludeAttachedActors' 'bool' 'true'
$l1 = ArrayLoop $ga 'OutActors' 300 900
Wire $rdw 'then' $l1.Loop 'execute'; Wire $bfw 'else' $l1.Loop 'execute'
$gc = Call '/Script/Engine.Actor' 'K2_GetComponentsByClass' 1000 1120; Wire $l1.Item 'Output' $gc 'self'
Def $gc 'ComponentClass' 'class:/Script/Engine.ActorComponent' '/Script/Engine.SkeletalMeshComponent'
$l2 = ArrayLoop $gc 'ReturnValue' 1300 900
Wire $l1.Loop 'LoopBody' $l2.Loop 'execute'
$ca = Cast '/Script/Engine.SkeletalMeshComponent' 2000 900; Wire $l2.Loop 'LoopBody' $ca 'execute'; Wire $l2.Item 'Output' $ca 'Object'
$nm = Call '/Script/Engine.PrimitiveComponent' 'GetNumMaterials' 1400 1060; Wire $ca 'AsSkeletal Mesh Component' $nm 'self'
$sb = Call $KM 'Subtract_IntInt' 1600 1060; Wire $nm 'ReturnValue' $sb 'A'; Def $sb 'B' 'int' '1'
$fl = Macro 'ForLoop' '' 1800 900; Wire $ca 'then' $fl 'execute'; Def $fl 'FirstIndex' 'int' '0'; Wire $sb 'ReturnValue' $fl 'LastIndex'
$cm = Call '/Script/Engine.PrimitiveComponent' 'CreateDynamicMaterialInstance' 2050 900
Wire $fl 'LoopBody' $cm 'execute'; Wire $ca 'AsSkeletal Mesh Component' $cm 'self'; Wire $fl 'Index' $cm 'ElementIndex'
# the vanilla texture comes off the MID's PARENT: after one swap the MID itself
# holds the imported Texture2D_N, which is why a second F6 used to do nothing
$pg = GetVarOf '/Script/Engine.MaterialInstance' 'Parent' 2300 1060; Wire $cm 'ReturnValue' $pg 'self'
$c2 = Cast $MIC 2500 900; Wire $cm 'then' $c2 'execute'; Wire $pg 'Parent' $c2 'Object'
$ba = Branch 2750 900; Wire $c2 'then' $ba 'execute'; Wire $e 'Announce' $ba 'Condition'
# announce: t_<BaseColor texture name>
$gt = Call $MIC 'K2_GetTextureParameterValue' 3000 800; Wire $ba 'then' $gt 'execute'; Wire $c2 'AsMaterial Instance Constant' $gt 'self'
Def $gt 'ParameterName' 'name' 'BaseColor'
$iv = Call $KS 'IsValid' 3250 700; Wire $gt 'ReturnValue' $iv 'Object'
$bv = Branch 3300 800; Wire $gt 'then' $bv 'execute'; Wire $iv 'ReturnValue' $bv 'Condition'
$on = Call $KS 'GetObjectName' 3300 700; Wire $gt 'ReturnValue' $on 'Object'
$tc = Concat-Chain @('t_', @($on, 'ReturnValue')) 3300 620
$sc = CallSelf 'SendCmd' 3550 800; Wire $bv 'then' $sc 'execute'; Wire $tc 'ReturnValue' $sc 'Cmd'
# refresh: colour, shine and glow maps, and the dye mask - material colour
# edits are baked into the BaseColor PNG and DyeingTexture gets a blank
# (alpha 0 = undyed, proven in game 2026-09-24) so the game's dye does not
# paint over the bake
$prev = $ba; $prevPin = 'else'; $k = 0
foreach ($param in @('BaseColor', 'SpecularTexture', 'Emissive', 'DyeingTexture')) {
    $t = CallSelf 'TrySwap' (3000 + 260 * $k) 1100
    Wire $prev $prevPin $t 'execute'; Wire $cm 'ReturnValue' $t 'MID'; Wire $c2 'AsMaterial Instance Constant' $t 'MIC'
    Def $t 'Param' 'name' $param; Wire $e 'Force' $t 'Force'
    Wire $sel 'ReturnValue' $t 'Pak'; Wire $pxw 'Output' $t 'Prefix'
    $prev = $t; $prevPin = 'then'; $k++
}
# done: tell the PC
$bd = Branch 700 1600; Wire $l1.Loop 'Completed' $bd 'execute'; Wire $e 'Announce' $bd 'Condition'
$null = Send-Literal $bd 'then' 'tend' 950 1260
$null = Send-Literal $bd 'else' 'texok' 950 1400

# Close: hide, give the mouse back to the game. Only while open: the HUD counts
# Need/Stop calls, so a Stop without its Need would break the game's own menus.
$e = CustomEvent 'Close' 0 1700
$hvc = GetMember 'Hit' 0 1860
$ivc = Call $WG 'IsVisible' 150 1860; Wire $hvc 'Hit' $ivc 'self'
$bc = Branch 200 1700; Wire $e 'then' $bc 'execute'; Wire $ivc 'ReturnValue' $bc 'Condition'
$s1 = Set-Vis $bc 'then' 'Screen' 'Collapsed' 400 1700
$s2 = Set-Vis $s1 'then' 'Hit' 'Collapsed' 700 1700
$pc = Call $GS 'GetPlayerController' 900 2100; Def $pc 'PlayerIndex' 'int' '0'
$hg = Hud-Guard $pc 1000 1700; Wire $s2 'then' $hg.Branch 'execute'
# a MarvelHUD: its own Stop (stand-in ForceNetUpdate, renamed after the cook)
$stop = Call '/Script/Engine.Actor' 'ForceNetUpdate' 1900 1600
Wire $hg.Branch 'then' $stop 'execute'; Wire $hg.Hud 'ReturnValue' $stop 'self'
# anything else: the old way
$gm = Call $WB 'SetInputMode_GameOnly' 1900 1800; Wire $hg.Branch 'else' $gm 'execute'; Wire $pc 'ReturnValue' $gm 'PlayerController'
$cur = SetVarOf '/Script/Engine.PlayerController' 'bShowMouseCursor' 2150 1800
Wire $gm 'then' $cur 'execute'; Wire $pc 'ReturnValue' $cur 'self'; Def $cur 'bShowMouseCursor' 'bool' 'false'
$cl = Send-Literal $cur 'then' 'close' 2400 1700
Wire $stop 'then' $cl 'execute'

# MountLive: the in-game Build mod button's refresh (Project Galacta's method).
# The PC built the mod, packed its textures under fresh paths into
# <Content>\SkinStudioLive\paks\, wrote _pak.txt (<pak>|<order>|<prefix>|...)
# and raised SkinLiveMount. Mount that pak while the game runs, then answer
# mnt_true / mnt_false / mnt_nofile. The Tick runs this BEFORE the texture
# walk, so SLT_ flags raised with it already find the pak mounted.
# The mount is authored as a stand-in, GameplayStatics.DoesSaveGameExist(path,
# order) - the only stock (string, int) -> bool - and patch_live_calls.ps1 points
# THIS call (the one whose index is not a constant) at Rivals'
# NePatchUtility.MountPak(PakFilename, Order), the function Galacta calls.
$e = CustomEvent 'MountLive' 0 2300
$cdm = Call $KS 'GetProjectContentDirectory' 0 2460
$mfm = Concat-Chain @(@($cdm, 'ReturnValue'), 'SkinStudioLive/_pak.txt') 0 2460
$fem = Call '/Script/Engine.BlueprintPathsLibrary' 'FileExists' 300 2580; Wire $mfm 'ReturnValue' $fem 'InPath'
$bmm = Branch 250 2300; Wire $e 'then' $bmm 'execute'; Wire $fem 'ReturnValue' $bmm 'Condition'
$rdm = Call $KS 'GetConsoleVariableStringValue' 500 2300; Wire $bmm 'then' $rdm 'execute'; Wire $mfm 'ReturnValue' $rdm 'VariableName'
$pam = Call $KSt 'ParseIntoArray' 700 2460; Wire $rdm 'ReturnValue' $pam 'SourceString'; Def $pam 'Delimiter' 'string' '|'; Def $pam 'CullEmptyStrings' 'bool' 'false'
$g0m = Add-Node '/Script/BlueprintGraph.K2Node_GetArrayItem' @() 950 2460
Wire $pam 'ReturnValue' $g0m 'Array'; Def $g0m 'Dimension 1' 'int' '0'
$g1m = Add-Node '/Script/BlueprintGraph.K2Node_GetArrayItem' @() 950 2600
Wire $pam 'ReturnValue' $g1m 'Array'; Def $g1m 'Dimension 1' 'int' '1'
$pkm = Concat-Chain @(@($cdm, 'ReturnValue'), @($g0m, 'Output')) 1100 2460
$oim = Call $KSt 'Conv_StringToInt' 1200 2600; Wire $g1m 'Output' $oim 'InString'
$mtm = Call $GS 'DoesSaveGameExist' 1500 2300; Wire $rdm 'then' $mtm 'execute'
Wire $pkm 'ReturnValue' $mtm 'SlotName'; Wire $oim 'ReturnValue' $mtm 'UserIndex'
$bsm = Call $KSt 'Conv_BoolToString' 1700 2460; Wire $mtm 'ReturnValue' $bsm 'InBool'
$msm = Concat-Chain @('mnt_', @($bsm, 'ReturnValue')) 1700 2560
$scm = CallSelf 'SendCmd' 1950 2300; Wire $mtm 'then' $scm 'execute'; Wire $msm 'ReturnValue' $scm 'Cmd'
$null = Send-Literal $bmm 'else' 'mnt_nofile' 500 2700
Save-Graph 'editor_2.txt'

# =========================================================== editor, paste 3
New-Graph 3
# Open: only in a match - the lobby hero is not reachable, and changing the
# input mode on a menu screen could leave the menu without a cursor
$e = CustomEvent 'Open' 0 0
$pp = Call $GS 'GetPlayerPawn' 0 160; Def $pp 'PlayerIndex' 'int' '0'
$iv = Call $KS 'IsValid' 200 160; Wire $pp 'ReturnValue' $iv 'Object'
$b0 = Branch 250 0; Wire $e 'then' $b0 'execute'; Wire $iv 'ReturnValue' $b0 'Condition'
# right edge, vertically centred; 1x1 until the first frame sets the real size
$vs = Call $WL 'GetViewportSize' 400 200
$bv = Call $KM 'BreakVector2D' 600 200; Wire $vs 'ReturnValue' $bv 'InVec'
$mx = Call $KM 'Subtract_DoubleDouble' 800 200; Wire $bv 'X' $mx 'A'; Def $mx 'B' 'real' '24.000000'
$my = Call $KM 'Multiply_DoubleDouble' 800 320; Wire $bv 'Y' $my 'A'; Def $my 'B' 'real' '0.500000'
$mv = Call $KM 'MakeVector2D' 1000 200; Wire $mx 'ReturnValue' $mv 'X'; Wire $my 'ReturnValue' $mv 'Y'
$sp = Call $UW 'SetPositionInViewport' 500 0; Wire $b0 'then' $sp 'execute'; Wire $mv 'ReturnValue' $sp 'Position'; Def $sp 'bRemoveDPIScale' 'bool' 'true'
$sa = Call $UW 'SetAlignmentInViewport' 750 0; Wire $sp 'then' $sa 'execute'; Def $sa 'Alignment' 'struct:/Script/CoreUObject.Vector2D' '(X=1.000000,Y=0.500000)'
$sd = Call $UW 'SetDesiredSizeInViewport' 1000 0; Wire $sa 'then' $sd 'execute'; Def $sd 'Size' 'struct:/Script/CoreUObject.Vector2D' '(X=1.000000,Y=1.000000)'
$sh = Set-Vis $sd 'then' 'Hit' 'Visible' 1250 0
$pc = Call $GS 'GetPlayerController' 1450 200; Def $pc 'PlayerIndex' 'int' '0'
$hg = Hud-Guard $pc 1450 -300; Wire $sh 'then' $hg.Branch 'execute'
# a MarvelHUD: ask it for UI input mode the way the game's own menus do
# (stand-in RemoveTickPrerequisiteActor(None), renamed after the cook)
$need = Call '/Script/Engine.Actor' 'RemoveTickPrerequisiteActor' 2300 -400
Wire $hg.Branch 'then' $need 'execute'; Wire $hg.Hud 'ReturnValue' $need 'self'
# anything else: the old way
$im = Call $WB 'SetInputMode_GameAndUIEx' 2300 0; Wire $hg.Branch 'else' $im 'execute'; Wire $pc 'ReturnValue' $im 'PlayerController'
Def $im 'InMouseLockMode' 'byte:/Script/Engine.EMouseLockMode' 'DoNotLock'; Def $im 'bHideCursorDuringCapture' 'bool' 'false'; Def $im 'bFlushInput' 'bool' 'false'
$cur = SetVarOf '/Script/Engine.PlayerController' 'bShowMouseCursor' 2600 0
Wire $im 'then' $cur 'execute'; Wire $need 'then' $cur 'execute'; Wire $pc 'ReturnValue' $cur 'self'; Def $cur 'bShowMouseCursor' 'bool' 'true'
# open_<vw>_<vh>_<scale*100>
$vx = Call $KM 'Round' 1300 400; Wire $bv 'X' $vx 'A'
$vy = Call $KM 'Round' 1300 500; Wire $bv 'Y' $vy 'A'
$vscale = Call $WL 'GetViewportScale' 1100 600   # not $gs: that is $GS, the GameplayStatics path
$m100 = Call $KM 'Multiply_DoubleDouble' 1300 600; Wire $vscale 'ReturnValue' $m100 'A'; Def $m100 'B' 'real' '100.000000'
$vsr = Call $KM 'Round' 1500 600; Wire $m100 'ReturnValue' $vsr 'A'
$s1 = Call $KSt 'Conv_IntToString' 1500 400; Wire $vx 'ReturnValue' $s1 'InInt'
$s2 = Call $KSt 'Conv_IntToString' 1500 500; Wire $vy 'ReturnValue' $s2 'InInt'
$s3 = Call $KSt 'Conv_IntToString' 1700 600; Wire $vsr 'ReturnValue' $s3 'InInt'
$om = Concat-Chain @('open_', @($s1, 'ReturnValue'), '_', @($s2, 'ReturnValue'), '_', @($s3, 'ReturnValue')) 1700 400
$so = CallSelf 'SendCmd' 2850 0; Wire $cur 'then' $so 'execute'; Wire $om 'ReturnValue' $so 'Cmd'
$wk = CallSelf 'Walk' 3100 0; Wire $so 'then' $wk 'execute'; Def $wk 'Announce' 'bool' 'true'; Def $wk 'Force' 'bool' 'false'

# ReloadAll: F6 - re-import everything that has a PNG, flagged or not
$e = CustomEvent 'ReloadAll' 0 900
$wk = CallSelf 'Walk' 250 900; Wire $e 'then' $wk 'execute'; Def $wk 'Announce' 'bool' 'false'; Def $wk 'Force' 'bool' 'true'

# AutoStart: a hero just spawned - the bootstrap's AutoTick found a pawn it had
# not announced. Tell the PC which pawn (auto_<name>), then announce the hero's
# textures, the walk F8 does. The PC picks the design for that skin and flags
# its textures, and the Tick below paints them: the design is on the hero with
# no key pressed (her ask, 2026-09-26: it used to stay vanilla until F6/F8).
$e = CustomEvent 'AutoStart' 0 1300
$astP = Call $GS 'GetPlayerPawn' 0 1460; Def $astP 'PlayerIndex' 'int' '0'
$astN = Call $KS 'GetObjectName' 200 1460; Wire $astP 'ReturnValue' $astN 'Object'
$astC = Concat-Chain @('auto_', @($astN, 'ReturnValue')) 200 1560
$astS = CallSelf 'SendCmd' 450 1300; Wire $e 'then' $astS 'execute'; Wire $astC 'ReturnValue' $astS 'Cmd'
$astW = CallSelf 'Walk' 750 1300; Wire $astS 'then' $astW 'execute'; Def $astW 'Announce' 'bool' 'true'; Def $astW 'Force' 'bool' 'false'
Save-Graph 'editor_3.txt'

# =========================================================== editor, paste 4
New-Graph 4
# Toggle (F7)
$e = CustomEvent 'Toggle' 0 0
$hv = GetMember 'Hit' 0 160
$iv = Call $WG 'IsVisible' 180 160; Wire $hv 'Hit' $iv 'self'
$b = Branch 300 0; Wire $e 'then' $b 'execute'; Wire $iv 'ReturnValue' $b 'Condition'
$c = CallSelf 'Close' 550 -60; Wire $b 'then' $c 'execute'
$o = CallSelf 'Open' 550 80; Wire $b 'else' $o 'execute'

# Tick: new frame? close request? a built mod to mount? textures changed?
# mouse moved? (mount comes before the texture walk: the PC raises both at once)
$tk = OverrideEvent $UW 'Tick' 0 500
OutPin $tk 'InDeltaTime' 'float'
$sq = ExecSeq 250 500; Wire $tk 'then' $sq 'execute'
foreach ($n in 2..4) { [void](Get-Pin $sq ('then_' + $n) $true 'exec') }
# 0: frame
$dg = Flag-Check 'SkinLiveFrame' $sq 'then_0' 450 400
$cd = Call $KS 'GetProjectContentDirectory' 900 300
$fp = Concat-Chain @(@($cd, 'ReturnValue'), 'SkinStudioLive/_panel.png') 900 300
$imp = Call $KR 'ImportFileAsTexture2D' 1150 400; Wire $dg 'then' $imp 'execute'; Wire $fp 'ReturnValue' $imp 'Filename'
$ivt = Call $KS 'IsValid' 1400 300; Wire $imp 'ReturnValue' $ivt 'Object'
$bt = Branch 1450 400; Wire $imp 'then' $bt 'execute'; Wire $ivt 'ReturnValue' $bt 'Condition'
$scr = GetMember 'Screen' 1500 560
$sbt = Call '/Script/UMG.Image' 'SetBrushFromTexture' 1700 400
Wire $bt 'then' $sbt 'execute'; Wire $scr 'Screen' $sbt 'self'; Wire $imp 'ReturnValue' $sbt 'Texture'; Def $sbt 'bMatchSize' 'bool' 'false'
$sx = Call '/Script/Engine.Texture2D' 'Blueprint_GetSizeX' 1700 600; Wire $imp 'ReturnValue' $sx 'self'
$sy = Call '/Script/Engine.Texture2D' 'Blueprint_GetSizeY' 1700 700; Wire $imp 'ReturnValue' $sy 'self'
$dx = Call $KM 'Conv_IntToDouble' 1900 600; Wire $sx 'ReturnValue' $dx 'InInt'
$dy = Call $KM 'Conv_IntToDouble' 1900 700; Wire $sy 'ReturnValue' $dy 'InInt'
$vsc = Call $WL 'GetViewportScale' 1900 800
$qx = Call $KM 'Divide_DoubleDouble' 2100 600; Wire $dx 'ReturnValue' $qx 'A'; Wire $vsc 'ReturnValue' $qx 'B'
$qy = Call $KM 'Divide_DoubleDouble' 2100 700; Wire $dy 'ReturnValue' $qy 'A'; Wire $vsc 'ReturnValue' $qy 'B'
$sz = Call $KM 'MakeVector2D' 2300 600; Wire $qx 'ReturnValue' $sz 'X'; Wire $qy 'ReturnValue' $sz 'Y'
$sds = Call $UW 'SetDesiredSizeInViewport' 1950 400; Wire $sbt 'then' $sds 'execute'; Wire $sz 'ReturnValue' $sds 'Size'
# show the image only while open - a frame landing just after F7 closed the
# panel must not bring it back
$hv2 = GetMember 'Hit' 2150 540
$hvis = Call $WG 'IsVisible' 2300 540; Wire $hv2 'Hit' $hvis 'self'
$bo = Branch 2200 400; Wire $sds 'then' $bo 'execute'; Wire $hvis 'ReturnValue' $bo 'Condition'
$null = Set-Vis $bo 'then' 'Screen' 'HitTestInvisible' 2450 400
# 1: the panel's own close button
$dg = Flag-Check 'SkinLiveClose' $sq 'then_1' 450 900
$cl = CallSelf 'Close' 1000 900; Wire $dg 'then' $cl 'execute'
# 2: the Build mod button's pak, ready to mount
$dg = Flag-Check 'SkinLiveMount' $sq 'then_2' 450 1000
$mo = CallSelf 'MountLive' 1000 1000; Wire $dg 'then' $mo 'execute'
# 3: textures changed
$dg = Flag-Check 'SkinLiveTex' $sq 'then_3' 450 1100
$wk = CallSelf 'Walk' 1000 1100; Wire $dg 'then' $wk 'execute'; Def $wk 'Announce' 'bool' 'false'; Def $wk 'Force' 'bool' 'false'
# 4: mouse over the panel, at most 15 times a second - floor(t*15) changed
# since the last frame. Stateless, so the widget needs no variables at all.
$rt = Call $GS 'GetRealTimeSeconds' 450 1300
$m1 = Call $KM 'Multiply_DoubleDouble' 650 1300; Wire $rt 'ReturnValue' $m1 'A'; Def $m1 'B' 'real' '15.000000'
$f1 = Call $KM 'FFloor' 850 1300; Wire $m1 'ReturnValue' $f1 'A'
$sub = Call $KM 'Subtract_DoubleDouble' 650 1420; Wire $rt 'ReturnValue' $sub 'A'; Wire $tk 'InDeltaTime' $sub 'B'
$m2 = Call $KM 'Multiply_DoubleDouble' 850 1420; Wire $sub 'ReturnValue' $m2 'A'; Def $m2 'B' 'real' '15.000000'
$f2 = Call $KM 'FFloor' 1050 1420; Wire $m2 'ReturnValue' $f2 'A'
$ne = Call $KM 'NotEqual_IntInt' 1250 1300; Wire $f1 'ReturnValue' $ne 'A'; Wire $f2 'ReturnValue' $ne 'B'
$hv3 = GetMember 'Hit' 850 1560
$ih = Call $WG 'IsHovered' 1050 1560; Wire $hv3 'Hit' $ih 'self'
$ip = Call '/Script/UMG.Button' 'IsPressed' 1050 1660; Wire $hv3 'Hit' $ip 'self'
$or = Call $KM 'BooleanOR' 1250 1560; Wire $ih 'ReturnValue' $or 'A'; Wire $ip 'ReturnValue' $or 'B'
$and = Call $KM 'BooleanAND' 1450 1300; Wire $ne 'ReturnValue' $and 'A'; Wire $or 'ReturnValue' $and 'B'
$bm = Branch 1650 1300; Wire $sq 'then_4' $bm 'execute'; Wire $and 'ReturnValue' $bm 'Condition'
$sm = CallSelf 'SendMouse' 1900 1300; Wire $bm 'then' $sm 'execute'; Def $sm 'Verb' 'string' 'm'

# mouse buttons
$pe = BoundEvent 'Hit' 'OnPressed' 'OnButtonPressedEvent__DelegateSignature' 0 1900
$sm = CallSelf 'SendMouse' 400 1900; Wire $pe 'then' $sm 'execute'; Def $sm 'Verb' 'string' 'd'
$re = BoundEvent 'Hit' 'OnReleased' 'OnButtonReleasedEvent__DelegateSignature' 0 2050
$sm = CallSelf 'SendMouse' 400 2050; Wire $re 'then' $sm 'execute'; Def $sm 'Verb' 'string' 'u'

# wheel - never consumed, and ignored while the panel is closed
$y0 = 2250
foreach ($kw in @(@('MouseScrollUp', 'wu'), @('MouseScrollDown', 'wd'))) {
    $ik = InputKey $kw[0] $false 0 $y0
    $hv4 = GetMember 'Hit' 200 ($y0 + 140)
    $iv4 = Call $WG 'IsVisible' 380 ($y0 + 140); Wire $hv4 'Hit' $iv4 'self'
    $bw = Branch 350 $y0; Wire $ik 'Pressed' $bw 'execute'; Wire $iv4 'ReturnValue' $bw 'Condition'
    $null = Send-Literal $bw 'then' $kw[1] 600 $y0
    $y0 += 300
}
Save-Graph 'editor_4.txt'

# =========================================================== bootstrap
New-Graph 5
# breadcrumb: the class loaded and ran (SkinLiveInit.sav)
$oi = OverrideEvent $UW 'OnInitialized' 0 0
$l = Call $GS 'LoadGameFromSlot' 250 0; Def $l 'SlotName' 'string' 'HighlightSettings'; Def $l 'UserIndex' 'int' '0'; Wire $oi 'then' $l 'execute'
$s = Call $GS 'SaveGameToSlot' 500 0; Wire $l 'then' $s 'execute'; Wire $l 'ReturnValue' $s 'SaveGameObject'; Def $s 'SlotName' 'string' 'SkinLiveInit'; Def $s 'UserIndex' 'int' '0'
$initDone = $s      # the rest of OnInitialized is wired below, after Editor-Or-Create exists

function Editor-Or-Create($execFrom, [string]$execPin, [string]$callExisting, [string]$callNew, [int]$x, [int]$y) {
    # find the live editor widget; make it (added to the viewport, content
    # collapsed) when there is none yet - the bootstrap holds no variables
    $gw = Call $WB 'GetAllWidgetsOfClass' $x $y; Wire $execFrom $execPin $gw 'execute'
    Def $gw 'WidgetClass' 'class:/Script/UMG.UserWidget' $EditorClass; Def $gw 'TopLevelOnly' 'bool' 'false'
    $gi = Add-Node '/Script/BlueprintGraph.K2Node_GetArrayItem' @() ($x + 250) ($y + 160)
    Wire $gw 'FoundWidgets' $gi 'Array'; Def $gi 'Dimension 1' 'int' '0'
    $iv = Call $KS 'IsValid' ($x + 450) ($y + 160); Wire $gi 'Output' $iv 'Object'
    $b = Branch ($x + 300) $y; Wire $gw 'then' $b 'execute'; Wire $iv 'ReturnValue' $b 'Condition'
    # FoundWidgets is typed by WidgetClass (DeterminesOutputType), so no cast
    $c1 = CallEditor $callExisting ($x + 800) ($y - 80); Wire $b 'then' $c1 'execute'; Wire $gi 'Output' $c1 'self'
    $pc = Call $GS 'GetPlayerController' ($x + 450) ($y + 300); Def $pc 'PlayerIndex' 'int' '0'
    $cw = Add-Node '/Script/UMGEditor.K2Node_CreateWidget' @() ($x + 550) ($y + 120)
    Wire $b 'else' $cw 'execute'; Def $cw 'Class' "class:/Script/UMG.UserWidget" $EditorClass; Wire $pc 'ReturnValue' $cw 'OwningPlayer'
    $av = Call $UW 'AddToViewport' ($x + 800) ($y + 120); Wire $cw 'then' $av 'execute'; Wire $cw 'ReturnValue' $av 'self'; Def $av 'ZOrder' 'int' '50'
    $c2 = CallEditor $callNew ($x + 1050) ($y + 120); Wire $av 'then' $c2 'execute'; Wire $cw 'ReturnValue' $c2 'self'
}

# Project Galacta, installed alongside (her call 2026-09-26: both mods at once).
# Galacta and this mod both override WBP_UIDPanel and only one override loads:
# ours, because the container is named "!!SkinLive" and the engine mounts paks
# in reverse name order, so the first name mounts last and wins ties
# (FilePackageStore.cpp / IoDispatcherFileBackend.cpp, UE 5.3). Galacta's own
# panel exists only to host its widget as a collapsed child, so host it here
# instead: load its class by path and create it the same way. When Galacta is
# not installed the class does not load, the cast fails, and nothing happens.
$gcp = Call $KS 'MakeSoftClassPath' 700 -300; Def $gcp 'PathString' 'string' '/Game/Marvel/ProjectGalacta/UI/WBP_Galacta.WBP_Galacta_C'
$gcr = Call $KS 'Conv_SoftClassPathToSoftClassRef' 950 -300; Wire $gcp 'ReturnValue' $gcr 'SoftClassPath'
# AutoTick's once-a-second timer (the event is below): started first, so the
# Galacta host and the splash can never keep it from starting
$tmr = Call $KS 'K2_SetTimerDelegate' 650 -560; Wire $initDone 'then' $tmr 'execute'
Def $tmr 'Time' 'float' '1.000000'; Def $tmr 'bLooping' 'bool' 'true'
$glc = Call $KS 'LoadClassAsset_Blocking' 750 0; Wire $tmr 'then' $glc 'execute'; Wire $gcr 'ReturnValue' $glc 'AssetClass'
$gcc = Add-Node '/Script/BlueprintGraph.K2Node_ClassDynamicCast' @("TargetType=Class'`"/Script/UMG.UserWidget`"'") 1000 0
Wire $glc 'then' $gcc 'execute'; Wire $glc 'ReturnValue' $gcc 'Class'
# only one: the panel (and this bootstrap with it) is rebuilt on some screen
# changes, and a second Galacta widget would answer every key twice
$ggw = Call $WB 'GetAllWidgetsOfClass' 1250 0; Wire $gcc 'then' $ggw 'execute'; Wire $gcc 'AsUser Widget' $ggw 'WidgetClass'; Def $ggw 'TopLevelOnly' 'bool' 'false'
$ggl = CallArray 'Array_Length' 1450 160; Wire $ggw 'FoundWidgets' $ggl 'TargetArray'
$gge = Call $KM 'EqualEqual_IntInt' 1650 160; Wire $ggl 'ReturnValue' $gge 'A'; Def $gge 'B' 'int' '0'
$ggb = Branch 1500 0; Wire $ggw 'then' $ggb 'execute'; Wire $gge 'ReturnValue' $ggb 'Condition'
$gpc = Call $GS 'GetPlayerController' 1700 300; Def $gpc 'PlayerIndex' 'int' '0'
$gcw = Add-Node '/Script/UMGEditor.K2Node_CreateWidget' @() 1750 0
Wire $ggb 'then' $gcw 'execute'; Wire $gcc 'AsUser Widget' $gcw 'Class'; Wire $gpc 'ReturnValue' $gcw 'OwningPlayer'
# collapsed, as its own panel keeps it: it draws nothing until its menus open
$gsv = Call $WG 'SetVisibility' 2050 0; Wire $gcw 'then' $gsv 'execute'; Wire $gcw 'ReturnValue' $gsv 'self'; Def $gsv 'InVisibility' $VisEnum 'Collapsed'
$gav = Call $UW 'AddToViewport' 2300 0; Wire $gsv 'then' $gav 'execute'; Wire $gcw 'ReturnValue' $gav 'self'; Def $gav 'ZOrder' 'int' '0'

# our logo at login, on its own (Splash in the panel widget): only on the
# login level, which is what Galacta checks for its own intro too
# ★ GetCurrentLevelName is NOT pure in 5.3 (BlueprintCallable): it needs the
# exec line, or the compiler prunes it ("its Exec pin is not connected")
$glv = Call $GS 'GetCurrentLevelName' 2550 0; Def $glv 'bRemovePrefixString' 'bool' 'true'
Wire $gav 'then' $glv 'execute'; Wire $ggb 'else' $glv 'execute'; Wire $gcc 'CastFailed' $glv 'execute'
$glk = Call $KSt 'Contains' 2750 160; Wire $glv 'ReturnValue' $glk 'SearchIn'; Def $glk 'Substring' 'string' 'ClientEntry'
$glb = Branch 2800 0; Wire $glv 'then' $glb 'execute'
Wire $glk 'ReturnValue' $glb 'Condition'
Editor-Or-Create $glb 'then' 'Splash' 'Splash' 2850 0

# F6: reload every edited texture (also leaves a SkinLiveFired.sav breadcrumb)
$f6 = InputKey 'F6' $true 0 400
$l = Call $GS 'LoadGameFromSlot' 250 400; Def $l 'SlotName' 'string' 'HighlightSettings'; Def $l 'UserIndex' 'int' '0'; Wire $f6 'Pressed' $l 'execute'
$s = Call $GS 'SaveGameToSlot' 500 400; Wire $l 'then' $s 'execute'; Wire $l 'ReturnValue' $s 'SaveGameObject'; Def $s 'SlotName' 'string' 'SkinLiveFired'; Def $s 'UserIndex' 'int' '0'
Editor-Or-Create $s 'then' 'ReloadAll' 'ReloadAll' 750 400
# F8: the panel (was F7 - Project Galacta binds F7, and one press would hit both)
if (-not $Hosted) {
    $f8 = InputKey 'F8' $true 0 1000
    Editor-Or-Create $f8 'Pressed' 'Toggle' 'Open' 750 1000
}

# AutoTick: once a second, from the timer OnInitialized starts (this widget is
# never laid out, so it never gets a Tick of its own - timers still run). Two
# jobs, both answering a request left as a save slot, like every flag here:
#   0  SkinLiveGalToggle: Skin Studio is swapping a freshly built mod in and
#      wants Project Galacta's F7 pressed. Call Galacta's own
#      GAL_ModLoader.ToggleMods - the function its F7 runs - BY NAME (Set Timer
#      by Function Name), so nothing of Galacta's is needed to compile, and a
#      Galacta without it just logs a warning. gal_1 = pressed, gal_0 = no
#      Galacta loader in this level (Skin Studio then asks her to press F7).
#   1  while Skin Studio listens (SkinLiveOn): a hero spawned that nothing has
#      announced yet -> AutoStart on the panel widget. SLA_<pawn> marks it
#      announced (the PC drops the marker when the mesh was not attached yet,
#      so the next second asks again).
$atkE = CustomEvent 'AutoTick' 0 1500
Wire $atkE 'OutputDelegate' $tmr 'Delegate'
$atkSeq = ExecSeq 250 1500; Wire $atkE 'then' $atkSeq 'execute'
# 0: Galacta's F7
$atkF = Flag-Check 'SkinLiveGalToggle' $atkSeq 'then_0' 450 1500
$atkP = Call $KS 'MakeSoftClassPath' 900 1660; Def $atkP 'PathString' 'string' '/Game/Marvel/ProjectGalacta/Blueprints/GAL_ModLoader.GAL_ModLoader_C'
$atkR = Call $KS 'Conv_SoftClassPathToSoftClassRef' 1150 1660; Wire $atkP 'ReturnValue' $atkR 'SoftClassPath'
$atkL = Call $KS 'LoadClassAsset_Blocking' 1000 1500; Wire $atkF 'then' $atkL 'execute'; Wire $atkR 'ReturnValue' $atkL 'AssetClass'
$atkC = Add-Node '/Script/BlueprintGraph.K2Node_ClassDynamicCast' @("TargetType=Class'`"/Script/Engine.Actor`"'") 1250 1500
Wire $atkL 'then' $atkC 'execute'; Wire $atkL 'ReturnValue' $atkC 'Class'
$atkA = Call $GS 'GetAllActorsOfClass' 1500 1500; Wire $atkC 'then' $atkA 'execute'; Wire $atkC 'AsActor' $atkA 'ActorClass'
$atkN = CallArray 'Array_Length' 1700 1660; Wire $atkA 'OutActors' $atkN 'TargetArray'
$atkG = Call $KM 'Greater_IntInt' 1900 1660; Wire $atkN 'ReturnValue' $atkG 'A'; Def $atkG 'B' 'int' '0'
$atkB = Branch 1800 1500; Wire $atkA 'then' $atkB 'execute'; Wire $atkG 'ReturnValue' $atkB 'Condition'
$atkI = Add-Node '/Script/BlueprintGraph.K2Node_GetArrayItem' @() 1900 1780
Wire $atkA 'OutActors' $atkI 'Array'; Def $atkI 'Dimension 1' 'int' '0'
$atkT = Call $KS 'K2_SetTimer' 2100 1500; Wire $atkB 'then' $atkT 'execute'; Wire $atkI 'Output' $atkT 'Object'
Def $atkT 'FunctionName' 'string' 'ToggleMods'; Def $atkT 'Time' 'float' '0.050000'; Def $atkT 'bLooping' 'bool' 'false'
$null = Inline-Send $atkT 'then' @('gal_1') 2400 1500
$null = Inline-Send $atkB 'else' @('gal_0') 2400 1900
$null = Inline-Send $atkC 'CastFailed' @('gal_0') 1500 2200
# 1: a hero nothing has announced yet
$atkO = Call $GS 'DoesSaveGameExist' 450 2600; Def $atkO 'SlotName' 'string' 'SkinLiveOn'; Def $atkO 'UserIndex' 'int' '0'
Wire $atkSeq 'then_1' $atkO 'execute'
$atkOb = Branch 700 2600; Wire $atkO 'then' $atkOb 'execute'; Wire $atkO 'ReturnValue' $atkOb 'Condition'
$atkPp = Call $GS 'GetPlayerPawn' 700 2760; Def $atkPp 'PlayerIndex' 'int' '0'
$atkPv = Call $KS 'IsValid' 900 2760; Wire $atkPp 'ReturnValue' $atkPv 'Object'
$atkPb = Branch 950 2600; Wire $atkOb 'then' $atkPb 'execute'; Wire $atkPv 'ReturnValue' $atkPb 'Condition'
$atkPn = Call $KS 'GetObjectName' 1100 2760; Wire $atkPp 'ReturnValue' $atkPn 'Object'
$atkK = Concat-Chain @('SLA_', @($atkPn, 'ReturnValue')) 1100 2860
$atkD = Call $GS 'DoesSaveGameExist' 1200 2600; Wire $atkPb 'then' $atkD 'execute'; Wire $atkK 'ReturnValue' $atkD 'SlotName'; Def $atkD 'UserIndex' 'int' '0'
$atkDb = Branch 1450 2600; Wire $atkD 'then' $atkDb 'execute'; Wire $atkD 'ReturnValue' $atkDb 'Condition'
# the marker first, so a slow announce is never started twice
$atkLg = Call $GS 'LoadGameFromSlot' 1650 2600; Def $atkLg 'SlotName' 'string' 'HighlightSettings'; Def $atkLg 'UserIndex' 'int' '0'
Wire $atkDb 'else' $atkLg 'execute'
$atkSv = Call $GS 'SaveGameToSlot' 1900 2600; Wire $atkLg 'then' $atkSv 'execute'; Wire $atkLg 'ReturnValue' $atkSv 'SaveGameObject'
Wire $atkK 'ReturnValue' $atkSv 'SlotName'; Def $atkSv 'UserIndex' 'int' '0'
Editor-Or-Create $atkSv 'then' 'AutoStart' 'AutoStart' 2150 2600
Save-Graph 'bootstrap.txt'
